---
- hosts: all
  gather_facts: true

  tasks:
    - name: Remove SMBv1 Support
      win_feature:
        name: FS-SMB1
        state: absent
        become: yes

    - name: Install all security, critical, rollup, and definition updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - DefinitionUpdates
        state: installed
        become: yes